[build-system]
requires = ["setuptools >= 80.9.0"]
build-backend = "setuptools.build_meta"

[project]
name = "kymnasium"
dependencies = [
    "gymnasium >= 1.2.0",
    "pygame >= 2.6.1",
    "minigrid >= 3.0.0",
    "numpy >= 2.0.2",
    "pymunk >= 7.1.0",
    "rpyc >= 6.0.2"
]
description = "The collection of reinforcement learning environments developed for the Artificial Intelligence course at the Department of Computer Science and Engineering, Kangwon National University."
authors = [
    {name = "Woohyeok Choi", email = "woohyeok.choi@kangwon.ac.kr"},
]
maintainers = [
    {name = "Woohyeok Choi", email = "woohyeok.choi@kangwon.ac.kr"}
]
readme = "README.md"
license = "MIT AND (Apache-2.0 OR BSD-2-Clause)"
requires-python = ">= 3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
keywords = ["Environment, Agent, Reinforcement Learning, Gymnasium"]
dynamic = ["version"]


[project.urls]
Homepage = "https://knu-p4c-lab.github.io/"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["kymnasium*"]

[tool.setuptools.package-data]
"*" = ["*.csv", "*.ogg", "*.png"]